version: "2"

services:
    webapp:
        container_name: "daq-dotnet"
        image: "microsoft/dotnet:latest"
        ports:
            - "127.0.0.1:5000:5000"
        volumes: 
            - "./:/app"
        build:
            context: .
            dockerfile: "Dockerfile"
        entrypoint:
            - /app/startup.sh
